[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
optimizer_runs = 200
verbosity = 3 # display errors
match_contract = "Unit" # only runs unit tests by default
sizes = true
fs_permissions = [{ access = "read", path = "./"}]

[profile.CI] # run via FOUNDRY_PROFILE=CI foundry test
match_contract = "Unit || Fork" 

# See more config options https://github.com/foundry-rs/foundry/tree/master/config